select = [
    "C4",      # flake8-comprehensions
    "E",       # pycodestyle
    "F",       # pyflakes
    "G",       # flake8-logging-format
    "I",       # isort
    "ICN",     # flake8-import-conventions
    "ISC",     # flake8-implicit-str-concat
    "PIE",     # flake8-pie
    "PLE",     # pylint errors
]

# Never enforce `E501` (line length violations).
ignore = ["E501", "E731"]
