select = [
    "C4",      # flake8-comprehensions
    "E",       # pycodestyle
    "F",       # pyflakes
    "G",       # flake8-logging-format
]

# Never enforce `E501` (line length violations).
ignore = ["E501", "E731"]
