# Generated by Django 3.2.3 on 2021-06-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packages', '0001_squashed_0003_auto_20170524_0704'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlagDenylist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keyword', models.CharField(max_length=255)),
            ],
        ),
    ]
