# Generated by Django 2.2 on 2019-04-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='repo',
            name='public_testing',
            field=models.BooleanField(default=False, help_text='Is this repo meant for package testing (without signoffs)?'),
        ),
    ]
