# Generated by Django 2.2.5 on 2019-10-09 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_repo_public_testing'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageSecurity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pie', models.BooleanField(default=False)),
                ('relro', models.PositiveIntegerField(choices=[(1, 'No RELRO'), (2, 'Partial RELRO'), (2, 'Full RELRO')], default=1)),
                ('canary', models.BooleanField(default=False)),
                ('fortify', models.BooleanField(default=False)),
                ('pkg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Package')),
            ],
            options={
                'db_table': 'package_security',
            },
        ),
    ]
