# Generated by Django 2.2.6 on 2019-10-12 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_packagesecurity'),
    ]

    operations = [
        migrations.AddField(
            model_name='packagesecurity',
            name='filename',
            field=models.CharField(default='', max_length=1024),
        ),
    ]
