# Generated by Django 3.1.5 on 2021-01-31 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_rebuilderdstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='rebuilderdstatus',
            name='build_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
