# Generated by Django 3.2 on 2021-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rebuilderdstatus_build_id'),
        ('main', '0004_soname'),
    ]

    operations = [
    ]
