# Generated by Django 5.2.13 on 2026-04-11 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_0004_rebuilderdstatus_build_id_0004_soname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='repo',
            name='svn_root',
        ),
    ]
