# Generated by Django 2.2.6 on 2019-11-24 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devel', '0003_auto_20191009_1924'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='website_rss',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
