# Generated by Django 3.0.7 on 2020-06-28 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devel', '0004_userprofile_website_rss'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='website_rss',
            field=models.CharField(blank=True, help_text='RSS Feed of your website for planet.archlinux.org', max_length=200, null=True),
        ),
    ]
