# Generated by Django 3.0.7 on 2020-06-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devel', '0005_auto_20200628_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='rebuilderd_updates',
            field=models.BooleanField(default=False, help_text='Receive reproducible build package updates'),
        ),
    ]
