# Generated by Django 4.1.6 on 2023-03-12 15:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("devel", "0009_alter_userprofile_public_email_and_more"),
        ("devel", "0009_alter_userprofile_time_zone_alter_userprofile_yob"),
    ]

    operations = []
