# Generated by Django 3.0.6 on 2020-05-22 22:14

import devel.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('releng', '0002_auto_20181216_1605'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='pgp_key',
            field=devel.fields.PGPKeyField(blank=True, help_text='consists of 40 hex digits; use `gpg --fingerprint`', max_length=40, null=True, verbose_name='PGP key fingerprint'),
        ),
    ]
