# Generated by Django 4.0 on 2022-01-03 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releng', '0004_release_wkd_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='release',
            name='b2_sum',
            field=models.CharField(blank=True, max_length=128, verbose_name='B2 digest'),
        ),
        migrations.AddField(
            model_name='release',
            name='sha256_sum',
            field=models.CharField(blank=True, max_length=64, verbose_name='SHA256 digest'),
        ),
    ]
