# Generated by Django 4.0.4 on 2022-06-20 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('releng', '0005_release_b2_sum_release_sha256_sum'),
    ]

    operations = [
        migrations.AlterField(
            model_name='release',
            name='b2_sum',
            field=models.CharField(blank=True, max_length=128, verbose_name='BLAKE2b digest'),
        ),
    ]
