# Generated by Django 3.1.5 on 2021-01-31 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolists', '0001_squashed_0002_remove_todolist_old_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='kind',
            field=models.SmallIntegerField(choices=[(0, 'Rebuild'), (1, 'Task')], default=0,
                                           help_text='(Rebuild for soname bumps, Task for independent tasks)'),
        ),
    ]
