name: Github-Actions

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        submodules: recursive
        persist-credentials: false
    - name: Set up Python 3.14
      uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
      with:
        python-version: 3.14
    - name: Install uv
      id: setup-uv
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        version: "0.7.19"
        enable-cache: true
    - name: Install dependencies
      if: steps.setup-uv.outputs.cache-hit != 'true'
      run: uv sync
    - name: Run ruff
      run: |
        uv run ruff check .
    - name: Lint with flake8
      run: |
        make lint
    - name: Run collectstatic
      run: |
        make collectstatic
    - name: Run tests
      run: |
        make coverage
